name: Build and Deploy to staging
on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    name: Build and Deploy
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: |
          export REACT_APP_BASE_URL=https://${{ secrets.SSH_DEPLOY_HOST_STAGING }}/app/v1
          export REACT_APP_GOOGLE_DRIVE_CLIENT_ID=${{ secrets.REACT_APP_GOOGLE_DRIVE_CLIENT_ID }}
          export REACT_APP_GOOGLE_DRIVE_API_KEY=${{ secrets.REACT_APP_GOOGLE_DRIVE_API_KEY }}
          CI=false npm run build

      - name: Create heartbeat file
        run: |
          echo "DATE=$(date)" > build/heartbeat.txt
          echo "GH_SHA=$(git rev-parse HEAD)" >> build/heartbeat.txt

      - name: Copy file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_DEPLOY_HOST_STAGING }}
          port: ${{ secrets.DEPLOY_HOST_PORT_STAGING }}
          username: ${{ secrets.SSH_DEPLOY_USER_NAME_STAGING }}
          password: ${{ secrets.DEPLOY_USER_PASSWORD_STAGING }}
          source: build/*
          target: ${{ secrets.SSH_DEPLOY_PATH_STAGING }}

      - name: Copy backend heartbeat to web main dir 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_DEPLOY_HOST_STAGING }}
          username: ${{ secrets.SSH_DEPLOY_USER_NAME_STAGING }}
          password: ${{ secrets.DEPLOY_USER_PASSWORD_STAGING }}
          port: ${{ secrets.DEPLOY_HOST_PORT_STAGING }}
          script: |
            cp www/heartbeat-be.txt www/build/.
